<?php

declare(strict_types=1);

/* @var Magento\Checkout\Block\Cart\Shipping $block */
/* @var \Magento\Framework\Escaper $escaper */

try {
    $serializedCheckoutConfig = $block->getSerializedCheckoutConfig();
} catch (Exception) {
    $serializedCheckoutConfig = false;
}
?>

<?php if ($serializedCheckoutConfig): ?>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig(); ?>;
</script>
<?php endif; ?>
