<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/**  @var Template $block */
?>

<div id="cart-form-container" class="cart-component-container form form-cart" data-bind="scope:'checkout-cart-form'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <div class="separator"></div>
</div>

<script type="text/x-magento-init">
    {
        "#cart-form-container": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
