<?php

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Custom Cart'); ?>
<?php if ($_product->isSaleable()):?>
    <button type="submit"
            title="<?= $escaper->escapeHtmlAttr($buttonTitle) ?>"
            class="action secondary tocart customcart"
            id="product-addtocustomcart-button" disabled>
        <span><?= $escaper->escapeHtml($buttonTitle) ?></span>
    </button>
    <?= $block->getChildHtml('', true) ?>
<?php endif; ?>
